### PR TITLE
feat: add a default private key using the hardhat

### LINKED ISSUE #13: feat: add a default private key using the hardhat first address from the node list
Run this:
`npx hardhat node`

A list of private keys will be provided in order from 1 to 10, those are the default hardhat keys.

Take the first 3 keys and place them in the '.env.sample' file, we'll be using:
1st as Deployer
2nd as Trade Creator
3rd as Trade Acceptee

They should be implemented in the hardhat config file

### PR DESCRIPTION
**Pull request by Mitish98**
close #13

### CODE REVIEW

**Review by 0xneves — CHANGES_REQUESTED** [review]
We decided to change the `Trade` keyword for `Swap` in #37 

Could you commit the change from TRADE into SWAP in both files?

**Comment by Mitish98** [comment]
> We decided to change the `Trade` keyword for `Swap` in #37
> 
> Could you commit the change from TRADE into SWAP in both files?

Yes, sure! 

But i think i do this in this pull request #59 ? 

If don't, i need to do another pull request?

**Comment by 0xneves** [comment]
> > We decided to change the `Trade` keyword for `Swap` in #37
> > Could you commit the change from TRADE into SWAP in both files?
> 
> Yes, sure!
> 
> But i think i do this in this pull request #59 ?
> 
> If don't, i need to do another pull request?

You should do in this pull request (#60)
Your commits on a branch sum up in the same PR

**Comment by Mitish98** [comment]
See if the change in the Pull Request is correct:

https://github.com/blockful-io/swaplace-contracts/pull/60/commits/b4f4b53b8fa8887186b7ffbace478700c46724d4

**Comment by 0xneves** [comment]
> See if the change in the Pull Request is correct:
> 
> [b4f4b53](https://github.com/blockful-io/swaplace-contracts/commit/b4f4b53b8fa8887186b7ffbace478700c46724d4)

Nooo, you made it even worse  😂
You mixed with the #54 pull request which is already closed and didn't fix what was asked

**Pull request closed without merging**
