### PR TITLE
doc: [ISSUE-137] Update readme

### PR DESCRIPTION
**Pull request by 0xjoaovpsantos**
- [x] Change the TLDR: into TL;DR
- [x] Add more features, like create swap, accept swap
- [x] Describe the other fields, use example from the Uniswap Permit2

If you suggest more thing to add :)

### CODE REVIEW

**Comment by 0xneves** [comment]
@0xjoaovpsantos Thank you! 🥂 

Did some minor improvements on commit 4d7a4246763f29ccdbe623f52c97ba90d7246e13

**Comment by 0xjoaovpsantos** [comment]
@0xneves Thank you man!! Sorry by my english, i'm improving rsrsrsrs

**Comment by 0xneves** [comment]
Closes #137

**Comment by 0xneves** [comment]
> @0xneves Thank you man!! Sorry by my english, i'm improving rsrsrsrs

You good bro :D

**Pull request merged**
