### PR TITLE
feature: nodejs docs

### LINKED ISSUE #139: docs: add full NodeJS documentation in the README.md file
- ideal to add also documentation for NodeJS not only for Yarn.

### PR DESCRIPTION
**Pull request by luislucena16**
hey @0xneves all nodejs documentation is already added!

PR: https://github.com/blockful-io/swaplace-contracts/issues/139

closes #139

### CODE REVIEW

**Review by 0xneves — CHANGES_REQUESTED** [review]
In recent readme update at #148 there were updates that conflicts with this PR. Please update the branch prior to submitting this PR.

**Comment by luislucena16** [comment]
hey @0xneves the branch is already up to date! i checked it!
branch updated

**Comment by 0xneves** [comment]
> hey @0xneves the branch is already up to date! i checked it! branch updated

Yoo @luislucena16, your fork might not be up to date with the mainstream. Check the TL;DR, it's on the top, and yours is on the bottom. 
I did a [diff checker ](https://www.diffchecker.com/uh97ynsQ/) where you can see the differences.

**Comment by luislucena16** [comment]
hey @0xneves I think that's it, I've checked how it is in `main`

**Comment by 0xneves** [comment]
It is still different from the main branch :(
Don't just copy-paste the tldr into your commit. Try copying the main branch's readme, then add your changes to it.

image

**Comment by luislucena16** [comment]
hey @0xneves done! check it

**Review by 0xneves — APPROVED** [review]
Approving the changes after a slightly change on the installation part to make it smaller and linear

**Pull request merged**
